-- ============================================================================
-- Third seed: employers already posting to remote-first job boards.
--
-- Candidate list built from the 599 slug variants of companies our own feeds
-- already surface -- i.e. companies demonstrably willing to hire remotely. That
-- turns out to matter far more than the ATS vendor does:
--
--   hand-picked remote-first   29 boards   1,359 postings   139 worldwide  (10%)
--   feed employers (this one)  99 boards   5,617 postings    63 worldwide  (1.1%)
--   general YC startups       302 boards   7,174 postings    10 worldwide  (0.1%)
--
-- Hyphen variants of one slug are collapsed: two rows polling the same board
-- would list every posting twice.
-- ============================================================================

insert into companies (name, domain, ats_type, ats_token) values
    ('Airapps', null, 'ASHBY', 'airapps'),
    ('Ateam', null, 'ASHBY', 'ateam'),
    ('B2spin', null, 'ASHBY', 'b2spin'),
    ('Clarity', null, 'ASHBY', 'clarity'),
    ('Clera', null, 'ASHBY', 'clera'),
    ('Colonist', null, 'ASHBY', 'colonist'),
    ('Cribl', null, 'ASHBY', 'cribl'),
    ('Dualentry', null, 'ASHBY', 'dualentry'),
    ('Factory', null, 'ASHBY', 'factory'),
    ('Featherlessai', null, 'ASHBY', 'featherlessai'),
    ('Fin', null, 'ASHBY', 'fin'),
    ('Firstprinciples', null, 'ASHBY', 'firstprinciples'),
    ('Gr8 Tech', null, 'ASHBY', 'gr8-tech'),
    ('Headway', null, 'ASHBY', 'headway'),
    ('Hex', null, 'ASHBY', 'hex'),
    ('Hightouch', null, 'ASHBY', 'hightouch'),
    ('Novo', null, 'ASHBY', 'novo'),
    ('Orchard', null, 'ASHBY', 'orchard'),
    ('Pearl', null, 'ASHBY', 'pearl'),
    ('Stickermule', null, 'ASHBY', 'stickermule'),
    ('Testgorilla', null, 'ASHBY', 'testgorilla'),
    ('Thumbtack', null, 'ASHBY', 'thumbtack'),
    ('Welltech', null, 'ASHBY', 'welltech'),
    ('Algolia', null, 'GREENHOUSE', 'algolia'),
    ('Alpaca', null, 'GREENHOUSE', 'alpaca'),
    ('Asana', null, 'GREENHOUSE', 'asana'),
    ('Beyondfinance', null, 'GREENHOUSE', 'beyondfinance'),
    ('Bitwarden', null, 'GREENHOUSE', 'bitwarden'),
    ('Boldin', null, 'GREENHOUSE', 'boldin'),
    ('Carrotfertility', null, 'GREENHOUSE', 'carrotfertility'),
    ('Celonis', null, 'GREENHOUSE', 'celonis'),
    ('Checkr', null, 'GREENHOUSE', 'checkr'),
    ('Circleci', null, 'GREENHOUSE', 'circleci'),
    ('Collibra', null, 'GREENHOUSE', 'collibra'),
    ('Correlationone', null, 'GREENHOUSE', 'correlationone'),
    ('Costar', null, 'GREENHOUSE', 'costar'),
    ('Cribl', null, 'GREENHOUSE', 'cribl'),
    ('Current', null, 'GREENHOUSE', 'current'),
    ('Dremio', null, 'GREENHOUSE', 'dremio'),
    ('Ebanx', null, 'GREENHOUSE', 'ebanx'),
    ('Equummedical', null, 'GREENHOUSE', 'equummedical'),
    ('Expel', null, 'GREENHOUSE', 'expel'),
    ('Faire', null, 'GREENHOUSE', 'faire'),
    ('Finyard', null, 'GREENHOUSE', 'finyard'),
    ('Firstprinciples', null, 'GREENHOUSE', 'firstprinciples'),
    ('Generatebiomedicines', null, 'GREENHOUSE', 'generatebiomedicines'),
    ('Gr8tech', null, 'GREENHOUSE', 'gr8tech'),
    ('Gusto', null, 'GREENHOUSE', 'gusto'),
    ('Hightouch', null, 'GREENHOUSE', 'hightouch'),
    ('Huntress', null, 'GREENHOUSE', 'huntress'),
    ('Imagineworldwide', null, 'GREENHOUSE', 'imagineworldwide'),
    ('Infuse', null, 'GREENHOUSE', 'infuse'),
    ('Invisible', null, 'GREENHOUSE', 'invisible'),
    ('Iterable', null, 'GREENHOUSE', 'iterable'),
    ('Jfrog', null, 'GREENHOUSE', 'jfrog'),
    ('Keepersecurity', null, 'GREENHOUSE', 'keepersecurity'),
    ('Legion', null, 'GREENHOUSE', 'legion'),
    ('Lithic', null, 'GREENHOUSE', 'lithic'),
    ('Make', null, 'GREENHOUSE', 'make'),
    ('Melio', null, 'GREENHOUSE', 'melio'),
    ('Nebius', null, 'GREENHOUSE', 'nebius'),
    ('Nisc', null, 'GREENHOUSE', 'nisc'),
    ('Nomina', null, 'GREENHOUSE', 'nomina'),
    ('Okx', null, 'GREENHOUSE', 'okx'),
    ('Opencoreventures', null, 'GREENHOUSE', 'opencoreventures'),
    ('Oportun', null, 'GREENHOUSE', 'oportun'),
    ('Orchard', null, 'GREENHOUSE', 'orchard'),
    ('Pagerduty', null, 'GREENHOUSE', 'pagerduty'),
    ('Pingidentity', null, 'GREENHOUSE', 'pingidentity'),
    ('Platformsh', null, 'GREENHOUSE', 'platformsh'),
    ('Postscript', null, 'GREENHOUSE', 'postscript'),
    ('Princetonuniversity', null, 'GREENHOUSE', 'princetonuniversity'),
    ('Prove', null, 'GREENHOUSE', 'prove'),
    ('Qohash', null, 'GREENHOUSE', 'qohash'),
    ('Railsware', null, 'GREENHOUSE', 'railsware'),
    ('Redcellpartners', null, 'GREENHOUSE', 'redcellpartners'),
    ('Relationalai', null, 'GREENHOUSE', 'relationalai'),
    ('Revero', null, 'GREENHOUSE', 'revero'),
    ('Roblox', null, 'GREENHOUSE', 'roblox'),
    ('Saasgroup', null, 'GREENHOUSE', 'saasgroup'),
    ('Salesloft', null, 'GREENHOUSE', 'salesloft'),
    ('Samsara', null, 'GREENHOUSE', 'samsara'),
    ('Seatgeek', null, 'GREENHOUSE', 'seatgeek'),
    ('Spotter', null, 'GREENHOUSE', 'spotter'),
    ('Squarespace', null, 'GREENHOUSE', 'squarespace'),
    ('Tensorops', null, 'GREENHOUSE', 'tensorops'),
    ('Thinkacademyus', null, 'GREENHOUSE', 'thinkacademyus'),
    ('Tines', null, 'GREENHOUSE', 'tines'),
    ('Typeform', null, 'GREENHOUSE', 'typeform'),
    ('Veeamsoftware', null, 'GREENHOUSE', 'veeamsoftware'),
    ('Veracode', null, 'GREENHOUSE', 'veracode'),
    ('Vetto', null, 'GREENHOUSE', 'vetto'),
    ('Whitetech', null, 'GREENHOUSE', 'whitetech'),
    ('Wrike', null, 'GREENHOUSE', 'wrike'),
    ('Xometryeurope', null, 'GREENHOUSE', 'xometryeurope'),
    ('Zoominfo', null, 'GREENHOUSE', 'zoominfo'),
    ('Zscaler', null, 'GREENHOUSE', 'zscaler'),
    ('Zupinnovation', null, 'GREENHOUSE', 'zupinnovation'),
    ('Belkins', null, 'LEVER', 'belkins')
on conflict (ats_type, ats_token) do nothing;
